import Brittanie from './images/Brittanie.jpg'
import Kira from './images/Kira.jpg'

export default [
  {
    name: 'Brittanie Pham',
    image: Brittanie,
    dave: `Dave, where do I even start?! You've been such an inspiration to me. Thank you for always making class enjoyable and fun. Honestly, you're the best teacher I've ever had and I promise you I am not just saying that to be nice. You've always been more than happy to help every student with anything they needed, and we couldn't have asked for more. Podium is practically begging you to work there, plus you'd get to be with your best friend Jake that we all hear so much about, yet you still choose to stay with us. I can definitely tell you love what you do and I'm happy for you. I can't thank you enough. p.s. If I can get better at boarding and handle more than the bunny hill, lets hit the slopes. I'll invite Taylor and whoever else at DPL that wants to join. We can have a DPL shred day. I'll bring an epi pen in case you break out in hives. (I still can't believe you're allergic to the cold)`,
    marc: `Sup Marc. I remember being nervous when I met you for the first time when you were interviewing me for DPL, but look at us now! From being complete strangers, to showing me around the place, and then to partying at EDC together. I’m definitely looking forward to making more memories with you. Thanks for always being so nice to me. I can’t wait to break our necks at Das together!`,
    nhi: `There was this one time when I went to Code On before I signed up for the cohort, and you were going around asking the students for their emails. When you got to me, you asked for my name and email and I totally thought you were joking so I replied with something stupid like ‘I don’t have a name’ or something… but looking back at it now, you probably really didn’t remember who I was. If you didn’t, wow I was embarrassing. Lol. Anyways, thanks for being so chill, man. I’ll put in a good word for you with Anna. You better get your Das ticket soon! I heard she’s still single. ;)`,
    will: `Sup Will. I can’t thank you enough for everything you’ve done for me. We’re family now and I couldn’t be more happy about it! Your positive vibes definitely spread to everyone around you and that’s why I love spending time with you. I can tell you love all of the students like we’re your kids and we love you too. Thanks for always wanting the best for us. You’re truly one of the nicest people I’ve ever met.`,
    anthony: `Oh boy, finding nice things to say about you is going to be hard… Just kidding! I’m sorry if I was ever mean to you, it’s just so easy to tease you, man. I feel like you set it up for me. I can’t help it. I hope you know that I only mess with you so much because I feel close/comfortable enough with you to do so. I'll never admit this in person but you always will be one of my favorite people to be around because you’re so fun to talk to! Anyways, thank you for always going above and beyond when I had questions. You are so smart, and an amazing TA/instructor! I might've had a bad way of showing it but, you definitely were one of my absolute favorite TA's. To be honest, I was always hoping to be in your group again, week after week.. but after the Casino game, I never got the chance! I was also pretty bummed when I found out we weren’t on the same portfolio project. Let’s be real, you probably planned it that way because of the trauma/emotional damage I caused you. Sorry dude. I’ll work on being a little less salty.`,
    dan: `Hey Dan! I remember feeling completely lost and hopeless at one point and you were the one that reassured me it was going to be okay. You definitely made me feel better by saying it was completely normal to feel that way and put me at ease. Thanks for being so cool. PS. I listened to a couple songs from your band on Spotify. You’ve got some pretty sick guitar skills!`,
    jacob: `Hey Jacob! First things first, I like your beard. It looks like it must’ve taken a lot of time to grow out. Anyways, thanks for being so chill, man. I remember being sooo nervous when I went through my first mock interview with you… but outside of that room, I absolutely loved being around you. Your positivity definitely fills the room. I wish I could’ve talked to you more this cohort! I think my favorite memory of you would be when you and Anthony put up monkeys on the big screen for us to watch live while we worked on our assessment. You both are so light-hearted. Thank you for making my experience at DPL so fun.`,
    sarah: `Sarah, you are one of the sweetest people I’ve ever met. Your personality is so light and bubbly! You always have such kind words to say to me and they definitely helped me feel better about myself when I had doubts. Even when I went through my mock interview with you, I didn’t feel as nervous because you were so pleasant to be around!`,
    spencer: `SPENNY! Where do I even start. You’re so cool, dude. I feel like I’ve known you for forever and it’s only been like 3 months. Thanks for making my experience at DPL so great. I know I can always count on you to either help me with my questions or even just to lighten my mood by talking. Your sense of humor is definitely one of my favorites.  No wonder you and Taylor get along so well. PS. I heard that your girlfriend was the one who painted my birthday present! She’s extremely talented. Tell her thank you for me. `
  },
  {
    name: 'Kira Kaur',
    image: Kira,
    dave: `Dave, you’re the best! You made coming to class and learning such a fun experience. I have learned so much from you in these past weeks, more than I thought I would be able to learn coming from a background of zero coding. You are kind, super smart, and an all-around awesome person to be around. You are an inspiration to me and so many others. Thank you so much for sharing your knowledge and helping us become programmers.`,
    marc: `Marc, you’re one of the coolest duded I’ve ever known. It was so fun talking about soccer with you. Your kindness and humor made DPL feel like a home more than a classroom. You were so helpful from the very beginning. Thank you for being so awesome!`,
    nhi: `Nhi, thank you for all of the hard work you put into making DPL so great. The time and dedication you put into giving as many possible resources to your students has made all the difference. I appreciate everything you did for myself and my classmates. Thank you so much!`,
    will: `Will, thank you so much for making DPL an amazing experience. Your kindness and dedication to your students was evident in every resource you provided to give us the best possible education and experience. I will always appreciate how much you cared about what you were doing and the students at DPL. Thank you so much!`,
    anthony: `Anthony, you are the best! Our banter was one of the favorite parts of my day. You were my favorite TA…but don’t tell the others. I appreciate the time you took to answer any and all of my questions until I understood the material and was no longer confused. Your patience and kindness made all the difference in helping me become a programmer. Thank you so much!`,
    dan: `Dan, thank you so much for being an awesome TA. You were always there to answer my questions and help me understand what was confusing me. You were such a fun guy to be around and learn from. Thank you so much for making my time at DPL so awesome.`,
    jacob: `Jacob, you are one of the coolest people I have met. Thank you so much for being patient and taking the time to answer all of my questions and help me learn. It was so fun getting to learn from you and know you. Thank you so much for being awesome!`,
    sarah: `Sarah, thank you so much for being an awesome TA this cohort. You helped me debug and understand so many things I was confused on. You took the time to not only answer my questions, but to help me learn how to answer them myself. I will always appreciate that. Thank you so much!`,
    spencer: `Spencer, thank you for being one of the funniest and coolest TA’s ever. You made learning so much fun and were always there to answer my questions and help me understand anything I was getting hung up on. Thank you so much!`
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  },
  {
    name: '',
    image: '',
    dave: '',
    marc: '',
    nhi: '',
    will: '',
    anthony: '',
    dan: '',
    jacob: '',
    sarah: '',
    spencer: ''
  }

]
